# Generated by Django 5.2 on 2025-04-06 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_course_enrolled_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='video',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='training_module',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='training_module',
        ),
        migrations.RemoveField(
            model_name='trainingmodule',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='trainingmodule',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='trainingmodule',
            name='vr_video_url',
        ),
        migrations.AddField(
            model_name='progress',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='training.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='training.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_modules', to='training.course'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='custom_course_id',
            field=models.CharField(default=1, help_text='Unique identifier for the course', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Duration in minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='module_thumbnails/'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='training.quiz'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='training.course')),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_modules', to='training.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TrainingVideo',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
