# Generated by Django 5.2 on 2025-04-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_userprogress_video_remove_userprogress_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmodule',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Duration in minutes'),
        ),
    ]
