# Generated by Django 5.2 on 2025-04-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_remove_progress_course_progress_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='module',
            new_name='course',
        ),
    ]
