# Generated by Django 5.2 on 2025-04-08 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_remove_quiz_course_course_image_course_post_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_by_users', to='training.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrolled_employees',
            field=models.ManyToManyField(blank=True, related_name='enrolled_in_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('trainer', 'Trainer')], default='employee', max_length=20),
        ),
    ]
