# Generated by Django 5.2 on 2025-04-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_remove_course_enrolled_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='course',
            name='post_test',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pre_test',
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
