# Generated by Django 5.2 on 2025-04-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_alter_course_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='post_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_quiz_courses', to='training.quiz'),
        ),
        migrations.AddField(
            model_name='course',
            name='pre_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_quiz_courses', to='training.quiz'),
        ),
    ]
