# Generated by Django 5.2 on 2025-04-09 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_course_post_quiz_course_pre_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='post_quiz',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pre_quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='training.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
