# Generated by Django 5.2 on 2025-04-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_alter_course_end_date_alter_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
