# Generated by Django 5.2 on 2025-04-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_videoprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
